baseURL = "https://reference.nirajankhatiwada.com.np/"
languageCode = "en-us"
title = "Quick Reference"
theme = "PaperMod"
author = "Nirajan Khatiwada"
description = "A cheatsheet blog for developers, offering quick references on various programming topics."
pagination.pagerSize = 10
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"  # Enables SEO features like Google Analytics, OpenGraph, etc.
  title = "Quick Reference"
  description = "Quick Reference is a developer-focused cheatsheet blog offering concise, actionable tips and guides on programming languages, web development, tools, and best practices. Explore fast and reliable references for developers of all skill levels."
  keywords =["Developer Cheatsheets", "Programming Resources", "Quick Reference for Developers", "Web Development Tips", "Coding Cheatsheets", "Programming Best Practices", "Developer Guides", "Programming Languages Cheatsheets"]
  author = "Nirajan Khatiwada"
  images = ["/images/shar.jpg"]  # OpenGraph and Twitter Cards image
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # SEO Enhancements
  enableSEO = true
  twitterCard = true
  opengraph = true

  [params.assets]
  favicon = "/images/icon.png"

  # Social Icons
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/__nirajan__"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/nirajan-khatiwada/"

  # Analytics (Optional)
  # [params.analytics.google]
  #   SiteVerificationTag = "XYZabc"

  # [params.analytics.bing]
  #   SiteVerificationTag = "XYZabc"

  # [params.analytics.yandex]
  #   SiteVerificationTag = "XYZabc"

  # Cover Image (Hidden in some sections)
  [params.cover]
    hidden = true  # Hide everywhere but not in structured data
    hiddenInList = true  # Hide on list pages and home
    hiddenInSingle = true  # Hide on single page

  # Edit Post Link
  [params.editPost]
    URL = "https://github.com/nirajan-khatiwada/quick-reference/content"
    Text = "Suggest Changes"  # Edit text
    appendFilePath = true  # Append file path to Edit link

  # Schema settings
  [params.schema]
    publisherType = "Organization"  # Correcting this to be a table

[params.homeInfoParams]
  Title = "Welcome, Developer 👨‍💻"
  Content = """
  Welcome to my developer-focused blog! Whether you're just starting out or are an experienced coder, this space is designed to help you find quick references, cheat sheets, and practical tips for various programming languages and tools.
  Here, you'll find guides that break down complex concepts into easy-to-understand examples, saving you time and boosting your productivity. My goal is to share valuable resources that streamline your coding journey, whether you're working on personal projects, preparing for interviews, or learning new technologies.
  Dive in, explore different topics, and feel free to use this blog as your go-to reference. Happy coding!
  """

[sitemap]
  changefreq = "monthly"
  priority = 0.5

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 10

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20
